#+TITLE: CFD with Python
#+AUTHOR: Sriram Krishnaswamy

This is a personal repository for learning the best practices in terms of Python and project management. I chose to do it in CFD because that's what I know.

For now, the aim of this repository is to provide well documented and tested code for some basic CFD purposes. I use [[https://github.com/sriramkswamy/CFDEGM6342][my codes from a graduate level CFD course]] and [[http://lorenabarba.com/blog/cfd-python-12-steps-to-navier-stokes/][Lorena Barba's course on CFD]]. In the future, I plan to include/fork some of the [[http://lorenabarba.com/code/][other works from her lab]]. The secondary goal is to follow some best practices when it comes to Git and GitHub such as proper branching, tagging releases, etc. Finally, I also intend to create a GitHub pages branch that uses Org mode to create literate programming examples.

- [X] Establish some goals in the README
- [ ] Start with UF CFD coursework
    - [ ] Add tests using [[http://pytest.org/latest/][py.test]]
    - [ ] Add documentation using [[http://www.sphinx-doc.org/en/stable/][sphinx]]
    - [ ] Release it as a library/module
    - [ ] Establish a =gh-pages= branch and add Org file explanations
- [ ] Start developing Lorena Barba's course in a new feature branch
    - [ ] Add lesson by lesson
    - [ ] Document each lesson's module and test the code (if applicable)
    - [ ] Add notes to the =gh-pages= page to build on top of the course videos and notes
- [ ] Check out the other works to see if something is interesting
- [ ] Maybe add this to the PyPI index?
